server:   # We need to apply additional config to ArgoCD helm chart to proxy traffic via Istio gateway
  extraArgs:
    - --staticassets
    - /shared/app
    - --redis
    - argocd-redis:6379
    - --insecure
    - --basehref
    - /argocd
    - --rootpath
    - /argocd
  env:
    - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
      value: "0"