apiVersion: v1
kind: Service
metadata:
  name: storage-service-v1.0
  namespace: prod-storage-service
  labels:
    app: storage-service
    version: v1.0
spec:
  selector:
    app: storage-service
    version: v1.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP