apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: prod
  labels:
    app: storage-service
    service: storage-service
spec:
  selector:
    app: storage-service  # One service per all deployments releases
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP