apiVersion: v1
kind: Service
metadata:
  name: user-service-v1.0
  namespace: prod-user-service
  labels:
    app: user-service
    version: v1.0
spec:
  selector:
    app: user-service
    version: v1.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP