apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: devops-project-cluster
  namespace: rabbitmq-system
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /etc/rabbitmq/definitions.json
                    subPath: definitions.json # Name of the ConfigMap field containing definitions
                    name: definitions
            volumes:
              - name: definitions
                configMap:
                  name: definitions # Name of the ConfigMap which contains definitions you wish to import
  rabbitmq:
    additionalConfig: |
      load_definitions = /etc/rabbitmq/definitions.json # Path to the mounted definitions file
      management.path_prefix = /rabbitmq # To route correctly via Gateway with our config we need to set path prefix