apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Cascade delete
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: devops-project
  source:
    repoURL: https://github.com/KacperKlimas10/DevOps.git
    targetRevision: feature/argocd-testing
    path: infrastructure/prod/kubernetes/user-service-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled  # To inject sidecar proxy automatically we need set this label
    syncOptions:
      - CreateNamespace=true