apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  labels:
    version: v2.17.0
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-project
  source:
    repoURL: https://github.com/KacperKlimas10/DevOps.git
    targetRevision: feature/argocd-testing
    path: infrastructure/prod/kubernetes/rabbitmq-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-system
        app.kubernetes.io/part-of: rabbitmq
    syncOptions:
      - CreateNamespace=true