apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Cascade delete
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: devops-project
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      releaseName: istio-ingressgateway
      values: |
        name: istio-ingressgateway
        labels:
          istio: ingressgateway
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true