apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
    - argocd.devops.kacperklimas.com
  gateways:
    - istio-ingress/argocd-gateway # In the virtual service documentation we can find information how to reference to gateway in other ns
  http:
    - match:
        - uri:
            prefix: /argocd
      route:
        - destination:
            host: argocd-server
            port:
              number: 80