apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
    - devops.kacperklimas.com
  gateways:
    - istio-ingress/application-gateway # In the virtual service documentation we can find information how to reference to gateway in other ns
  http:
    - match:
        - uri:
            prefix: /argocd
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80