apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: storage-service
  namespace: prod
spec:
  hosts:
    - devops.kacperklimas.com
  gateways:
    - istio-ingress/application-gateway # In the virtual service documentation we can find information how to reference to gateway in other ns
  http:
    - match:
        - uri:
            prefix: /api/storage
      route:
        - destination:
            host: storage-service.prod.svc.cluster.local
            subset: v1.0
          weight: 100   # We declare that all traffic is routed to v1.0 version
        - destination:
            host: storage-service.prod.svc.cluster.local
            subset: v2.0
          weight: 0
        - destination:
            host: storage-service.prod.svc.cluster.local
            subset: v3.0
          weight: 0