apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: storage-service
  namespace: prod
spec:
  hosts:
    - storage-service.prod.svc.cluster.local
  gateways:
    - prod/devops-gateway
  http:
    - match:
        - uri:
      route: