apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: management-ingress-gateway-cert
  namespace: argocd
spec:
  secretName: management-ingress-gateway-cert
  secretTemplate:
    labels:
      issuer: letsencrypt
  commonName: "argocd.devops.kacperklimas.com"
  dnsNames:
    - "argocd.devops.kacperklimas.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer