apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-ingress-gateway-cert
  namespace: istio-ingress
spec:
  secretName: app-ingress-gateway-cert
  secretTemplate:
    labels:
      issuer: letsencrypt
  commonName: "*.kacperklimas.com"
  dnsNames:
    - "*.kacperklimas.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer