apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-gateway-cert
  namespace: prod
spec:
  secretName: ingress-gateway-cert
  secretTemplate:
    labels:
      issuer: letencrypt
  commonName: "*.kacperklimas.com"
  dnsNames:
    - "*.kacperklimas.com"
  issuerRef:
    name: letsencrypt-issuer